/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as Programacao_do_eventoRouteImport } from './routes/programacao_do_evento'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PalestrantesRouteImport } from './routes/palestrantes'
import { Route as LocalRouteImport } from './routes/local'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const Programacao_do_eventoRoute = Programacao_do_eventoRouteImport.update({
  id: '/programacao_do_evento',
  path: '/programacao_do_evento',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestrantesRoute = PalestrantesRouteImport.update({
  id: '/palestrantes',
  path: '/palestrantes',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contato': typeof ContatoRoute
  '/inscricao': typeof InscricaoRoute
  '/local': typeof LocalRoute
  '/palestrantes': typeof PalestrantesRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao_do_evento': typeof Programacao_do_eventoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contato': typeof ContatoRoute
  '/inscricao': typeof InscricaoRoute
  '/local': typeof LocalRoute
  '/palestrantes': typeof PalestrantesRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao_do_evento': typeof Programacao_do_eventoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contato': typeof ContatoRoute
  '/inscricao': typeof InscricaoRoute
  '/local': typeof LocalRoute
  '/palestrantes': typeof PalestrantesRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao_do_evento': typeof Programacao_do_eventoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/contato'
    | '/inscricao'
    | '/local'
    | '/palestrantes'
    | '/parceiros'
    | '/programacao_do_evento'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/contato'
    | '/inscricao'
    | '/local'
    | '/palestrantes'
    | '/parceiros'
    | '/programacao_do_evento'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/contato'
    | '/inscricao'
    | '/local'
    | '/palestrantes'
    | '/parceiros'
    | '/programacao_do_evento'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ContatoRoute: typeof ContatoRoute
  InscricaoRoute: typeof InscricaoRoute
  LocalRoute: typeof LocalRoute
  PalestrantesRoute: typeof PalestrantesRoute
  ParceirosRoute: typeof ParceirosRoute
  Programacao_do_eventoRoute: typeof Programacao_do_eventoRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao_do_evento': {
      id: '/programacao_do_evento'
      path: '/programacao_do_evento'
      fullPath: '/programacao_do_evento'
      preLoaderRoute: typeof Programacao_do_eventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestrantes': {
      id: '/palestrantes'
      path: '/palestrantes'
      fullPath: '/palestrantes'
      preLoaderRoute: typeof PalestrantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ContatoRoute: ContatoRoute,
  InscricaoRoute: InscricaoRoute,
  LocalRoute: LocalRoute,
  PalestrantesRoute: PalestrantesRoute,
  ParceirosRoute: ParceirosRoute,
  Programacao_do_eventoRoute: Programacao_do_eventoRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
